#ifndef MRUBY_AUX_INTERNALS_PP_H
#define MRUBY_AUX_INTERNALS_PP_H 1

#define MRBX_IPP_EXPAND(...)            __VA_ARGS__

#define MRBX_IPP_JOIN_1(X, ...)         MRBX_IPP_JOIN_SELECTOR(__VA_ARGS__)(X, __VA_ARGS__)
#define MRBX_IPP_JOIN_SELECTOR(...)     MRBX_IPP_JOIN_SELECTOR_1(__VA_ARGS__,9,9,9,9,9,9,9,9,9,9,8,7,6,5,4,3,2,1,[[<<>>]])
#define MRBX_IPP_JOIN_SELECTOR_1(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,ARGC,...) MRBX_IPP_JOIN##ARGC
#define MRBX_IPP_JOIN1(T0,T1)                                 T0##T1
#define MRBX_IPP_JOIN2(T0,T1,T2)                              T0##T1##T2
#define MRBX_IPP_JOIN3(T0,T1,T2,T3)                           T0##T1##T2##T3
#define MRBX_IPP_JOIN4(T0,T1,T2,T3,T4)                        T0##T1##T2##T3##T4
#define MRBX_IPP_JOIN5(T0,T1,T2,T3,T4,T5)                     T0##T1##T2##T3##T4##T5
#define MRBX_IPP_JOIN6(T0,T1,T2,T3,T4,T5,T6)                  T0##T1##T2##T3##T4##T5##T6
#define MRBX_IPP_JOIN7(T0,T1,T2,T3,T4,T5,T6,T7)               T0##T1##T2##T3##T4##T5##T6##T7
#define MRBX_IPP_JOIN8(T0,T1,T2,T3,T4,T5,T6,T7,T8)            T0##T1##T2##T3##T4##T5##T6##T7##T8
#define MRBX_IPP_JOIN9(T0,T1,T2,T3,T4,T5,T6,T7,T8,T9)         T0##T1##T2##T3##T4##T5##T6##T7##T8##T9

#define MRBX_IPP_JOIN1_1(X, Y)          MRBX_IPP_JOIN1_2(X, Y)
#define MRBX_IPP_JOIN1_2(X, Y)          X ## Y

#define MRBX_IPP_CHOICE_EXPAND_1(COND, T, F) MRBX_IPP_CHOICE_EXPAND_2(MRBX_IPP_JOIN1_1(MRBX_IPP_CONDITION_, COND))(T, F)
#define MRBX_IPP_CHOICE_EXPAND_2(COND)  COND
#define MRBX_IPP_CONDITION_0(T, F)      MRBX_IPP_EXPAND F
#define MRBX_IPP_CONDITION_1(T, F)      MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_2(T, F)      MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_3(T, F)      MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_4(T, F)      MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_5(T, F)      MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_6(T, F)      MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_7(T, F)      MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_8(T, F)      MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_9(T, F)      MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_10(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_11(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_12(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_13(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_14(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_15(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_16(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_17(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_18(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_19(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_20(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_21(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_22(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_23(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_24(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_25(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_26(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_27(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_28(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_29(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_30(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_31(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_32(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_33(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_34(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_35(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_36(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_37(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_38(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_39(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_40(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_41(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_42(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_43(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_44(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_45(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_46(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_47(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_48(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_49(T, F)     MRBX_IPP_EXPAND T
#define MRBX_IPP_CONDITION_50(T, F)     MRBX_IPP_EXPAND T

#define MRBX_IPP_ONE_TO_0(F)
#define MRBX_IPP_ONE_TO_1(F)            MRBX_IPP_ONE_TO_0(F)  F(1)
#define MRBX_IPP_ONE_TO_2(F)            MRBX_IPP_ONE_TO_1(F)  F(2)
#define MRBX_IPP_ONE_TO_3(F)            MRBX_IPP_ONE_TO_2(F)  F(3)
#define MRBX_IPP_ONE_TO_4(F)            MRBX_IPP_ONE_TO_3(F)  F(4)
#define MRBX_IPP_ONE_TO_5(F)            MRBX_IPP_ONE_TO_4(F)  F(5)
#define MRBX_IPP_ONE_TO_6(F)            MRBX_IPP_ONE_TO_5(F)  F(6)
#define MRBX_IPP_ONE_TO_7(F)            MRBX_IPP_ONE_TO_6(F)  F(7)
#define MRBX_IPP_ONE_TO_8(F)            MRBX_IPP_ONE_TO_7(F)  F(8)
#define MRBX_IPP_ONE_TO_9(F)            MRBX_IPP_ONE_TO_8(F)  F(9)
#define MRBX_IPP_ONE_TO_10(F)           MRBX_IPP_ONE_TO_9(F)  F(10)
#define MRBX_IPP_ONE_TO_11(F)           MRBX_IPP_ONE_TO_10(F) F(11)
#define MRBX_IPP_ONE_TO_12(F)           MRBX_IPP_ONE_TO_11(F) F(12)
#define MRBX_IPP_ONE_TO_13(F)           MRBX_IPP_ONE_TO_12(F) F(13)
#define MRBX_IPP_ONE_TO_14(F)           MRBX_IPP_ONE_TO_13(F) F(14)
#define MRBX_IPP_ONE_TO_15(F)           MRBX_IPP_ONE_TO_14(F) F(15)
#define MRBX_IPP_ONE_TO_16(F)           MRBX_IPP_ONE_TO_15(F) F(16)
#define MRBX_IPP_ONE_TO_17(F)           MRBX_IPP_ONE_TO_16(F) F(17)
#define MRBX_IPP_ONE_TO_18(F)           MRBX_IPP_ONE_TO_17(F) F(18)
#define MRBX_IPP_ONE_TO_19(F)           MRBX_IPP_ONE_TO_18(F) F(19)
#define MRBX_IPP_ONE_TO_20(F)           MRBX_IPP_ONE_TO_19(F) F(20)
#define MRBX_IPP_ONE_TO_21(F)           MRBX_IPP_ONE_TO_20(F) F(21)
#define MRBX_IPP_ONE_TO_22(F)           MRBX_IPP_ONE_TO_21(F) F(22)
#define MRBX_IPP_ONE_TO_23(F)           MRBX_IPP_ONE_TO_22(F) F(23)
#define MRBX_IPP_ONE_TO_24(F)           MRBX_IPP_ONE_TO_23(F) F(24)
#define MRBX_IPP_ONE_TO_25(F)           MRBX_IPP_ONE_TO_24(F) F(25)
#define MRBX_IPP_ONE_TO_26(F)           MRBX_IPP_ONE_TO_25(F) F(26)
#define MRBX_IPP_ONE_TO_27(F)           MRBX_IPP_ONE_TO_26(F) F(27)
#define MRBX_IPP_ONE_TO_28(F)           MRBX_IPP_ONE_TO_27(F) F(28)
#define MRBX_IPP_ONE_TO_29(F)           MRBX_IPP_ONE_TO_28(F) F(29)
#define MRBX_IPP_ONE_TO_30(F)           MRBX_IPP_ONE_TO_29(F) F(30)
#define MRBX_IPP_ONE_TO_31(F)           MRBX_IPP_ONE_TO_30(F) F(31)
#define MRBX_IPP_ONE_TO_32(F)           MRBX_IPP_ONE_TO_31(F) F(32)
#define MRBX_IPP_ONE_TO_33(F)           MRBX_IPP_ONE_TO_32(F) F(33)
#define MRBX_IPP_ONE_TO_34(F)           MRBX_IPP_ONE_TO_33(F) F(34)
#define MRBX_IPP_ONE_TO_35(F)           MRBX_IPP_ONE_TO_34(F) F(35)
#define MRBX_IPP_ONE_TO_36(F)           MRBX_IPP_ONE_TO_35(F) F(36)
#define MRBX_IPP_ONE_TO_37(F)           MRBX_IPP_ONE_TO_36(F) F(37)
#define MRBX_IPP_ONE_TO_38(F)           MRBX_IPP_ONE_TO_37(F) F(38)
#define MRBX_IPP_ONE_TO_39(F)           MRBX_IPP_ONE_TO_38(F) F(39)
#define MRBX_IPP_ONE_TO_40(F)           MRBX_IPP_ONE_TO_39(F) F(40)
#define MRBX_IPP_ONE_TO_41(F)           MRBX_IPP_ONE_TO_40(F) F(41)
#define MRBX_IPP_ONE_TO_42(F)           MRBX_IPP_ONE_TO_41(F) F(42)
#define MRBX_IPP_ONE_TO_43(F)           MRBX_IPP_ONE_TO_42(F) F(43)
#define MRBX_IPP_ONE_TO_44(F)           MRBX_IPP_ONE_TO_43(F) F(44)
#define MRBX_IPP_ONE_TO_45(F)           MRBX_IPP_ONE_TO_44(F) F(45)
#define MRBX_IPP_ONE_TO_46(F)           MRBX_IPP_ONE_TO_45(F) F(46)
#define MRBX_IPP_ONE_TO_47(F)           MRBX_IPP_ONE_TO_46(F) F(47)
#define MRBX_IPP_ONE_TO_48(F)           MRBX_IPP_ONE_TO_47(F) F(48)
#define MRBX_IPP_ONE_TO_49(F)           MRBX_IPP_ONE_TO_48(F) F(49)
#define MRBX_IPP_ONE_TO_50(F)           MRBX_IPP_ONE_TO_49(F) F(50)

#define MRBX_IPP_ZERO_TO_0(F)           F(0)
#define MRBX_IPP_ZERO_TO_1(F)           MRBX_IPP_ZERO_TO_0(F)  F(1)
#define MRBX_IPP_ZERO_TO_2(F)           MRBX_IPP_ZERO_TO_1(F)  F(2)
#define MRBX_IPP_ZERO_TO_3(F)           MRBX_IPP_ZERO_TO_2(F)  F(3)
#define MRBX_IPP_ZERO_TO_4(F)           MRBX_IPP_ZERO_TO_3(F)  F(4)
#define MRBX_IPP_ZERO_TO_5(F)           MRBX_IPP_ZERO_TO_4(F)  F(5)
#define MRBX_IPP_ZERO_TO_6(F)           MRBX_IPP_ZERO_TO_5(F)  F(6)
#define MRBX_IPP_ZERO_TO_7(F)           MRBX_IPP_ZERO_TO_6(F)  F(7)
#define MRBX_IPP_ZERO_TO_8(F)           MRBX_IPP_ZERO_TO_7(F)  F(8)
#define MRBX_IPP_ZERO_TO_9(F)           MRBX_IPP_ZERO_TO_8(F)  F(9)
#define MRBX_IPP_ZERO_TO_10(F)          MRBX_IPP_ZERO_TO_9(F)  F(10)
#define MRBX_IPP_ZERO_TO_11(F)          MRBX_IPP_ZERO_TO_10(F) F(11)
#define MRBX_IPP_ZERO_TO_12(F)          MRBX_IPP_ZERO_TO_11(F) F(12)
#define MRBX_IPP_ZERO_TO_13(F)          MRBX_IPP_ZERO_TO_12(F) F(13)
#define MRBX_IPP_ZERO_TO_14(F)          MRBX_IPP_ZERO_TO_13(F) F(14)
#define MRBX_IPP_ZERO_TO_15(F)          MRBX_IPP_ZERO_TO_14(F) F(15)
#define MRBX_IPP_ZERO_TO_16(F)          MRBX_IPP_ZERO_TO_15(F) F(16)
#define MRBX_IPP_ZERO_TO_17(F)          MRBX_IPP_ZERO_TO_16(F) F(17)
#define MRBX_IPP_ZERO_TO_18(F)          MRBX_IPP_ZERO_TO_17(F) F(18)
#define MRBX_IPP_ZERO_TO_19(F)          MRBX_IPP_ZERO_TO_18(F) F(19)
#define MRBX_IPP_ZERO_TO_20(F)          MRBX_IPP_ZERO_TO_19(F) F(20)
#define MRBX_IPP_ZERO_TO_21(F)          MRBX_IPP_ZERO_TO_20(F) F(21)
#define MRBX_IPP_ZERO_TO_22(F)          MRBX_IPP_ZERO_TO_21(F) F(22)
#define MRBX_IPP_ZERO_TO_23(F)          MRBX_IPP_ZERO_TO_22(F) F(23)
#define MRBX_IPP_ZERO_TO_24(F)          MRBX_IPP_ZERO_TO_23(F) F(24)
#define MRBX_IPP_ZERO_TO_25(F)          MRBX_IPP_ZERO_TO_24(F) F(25)
#define MRBX_IPP_ZERO_TO_26(F)          MRBX_IPP_ZERO_TO_25(F) F(26)
#define MRBX_IPP_ZERO_TO_27(F)          MRBX_IPP_ZERO_TO_26(F) F(27)
#define MRBX_IPP_ZERO_TO_28(F)          MRBX_IPP_ZERO_TO_27(F) F(28)
#define MRBX_IPP_ZERO_TO_29(F)          MRBX_IPP_ZERO_TO_28(F) F(29)
#define MRBX_IPP_ZERO_TO_30(F)          MRBX_IPP_ZERO_TO_29(F) F(30)
#define MRBX_IPP_ZERO_TO_31(F)          MRBX_IPP_ZERO_TO_30(F) F(31)
#define MRBX_IPP_ZERO_TO_32(F)          MRBX_IPP_ZERO_TO_31(F) F(32)
#define MRBX_IPP_ZERO_TO_33(F)          MRBX_IPP_ZERO_TO_32(F) F(33)
#define MRBX_IPP_ZERO_TO_34(F)          MRBX_IPP_ZERO_TO_33(F) F(34)
#define MRBX_IPP_ZERO_TO_35(F)          MRBX_IPP_ZERO_TO_34(F) F(35)
#define MRBX_IPP_ZERO_TO_36(F)          MRBX_IPP_ZERO_TO_35(F) F(36)
#define MRBX_IPP_ZERO_TO_37(F)          MRBX_IPP_ZERO_TO_36(F) F(37)
#define MRBX_IPP_ZERO_TO_38(F)          MRBX_IPP_ZERO_TO_37(F) F(38)
#define MRBX_IPP_ZERO_TO_39(F)          MRBX_IPP_ZERO_TO_38(F) F(39)
#define MRBX_IPP_ZERO_TO_40(F)          MRBX_IPP_ZERO_TO_39(F) F(40)
#define MRBX_IPP_ZERO_TO_41(F)          MRBX_IPP_ZERO_TO_40(F) F(41)
#define MRBX_IPP_ZERO_TO_42(F)          MRBX_IPP_ZERO_TO_41(F) F(42)
#define MRBX_IPP_ZERO_TO_43(F)          MRBX_IPP_ZERO_TO_42(F) F(43)
#define MRBX_IPP_ZERO_TO_44(F)          MRBX_IPP_ZERO_TO_43(F) F(44)
#define MRBX_IPP_ZERO_TO_45(F)          MRBX_IPP_ZERO_TO_44(F) F(45)
#define MRBX_IPP_ZERO_TO_46(F)          MRBX_IPP_ZERO_TO_45(F) F(46)
#define MRBX_IPP_ZERO_TO_47(F)          MRBX_IPP_ZERO_TO_46(F) F(47)
#define MRBX_IPP_ZERO_TO_48(F)          MRBX_IPP_ZERO_TO_47(F) F(48)
#define MRBX_IPP_ZERO_TO_49(F)          MRBX_IPP_ZERO_TO_48(F) F(49)
#define MRBX_IPP_ZERO_TO_50(F)          MRBX_IPP_ZERO_TO_49(F) F(50)

#define MRBX_IPP_ONE_FROM_0(F)
#define MRBX_IPP_ONE_FROM_1(F)          F(1)  MRBX_IPP_ONE_FROM_0(F)
#define MRBX_IPP_ONE_FROM_2(F)          F(2)  MRBX_IPP_ONE_FROM_1(F)
#define MRBX_IPP_ONE_FROM_3(F)          F(3)  MRBX_IPP_ONE_FROM_2(F)
#define MRBX_IPP_ONE_FROM_4(F)          F(4)  MRBX_IPP_ONE_FROM_3(F)
#define MRBX_IPP_ONE_FROM_5(F)          F(5)  MRBX_IPP_ONE_FROM_4(F)
#define MRBX_IPP_ONE_FROM_6(F)          F(6)  MRBX_IPP_ONE_FROM_5(F)
#define MRBX_IPP_ONE_FROM_7(F)          F(7)  MRBX_IPP_ONE_FROM_6(F)
#define MRBX_IPP_ONE_FROM_8(F)          F(8)  MRBX_IPP_ONE_FROM_7(F)
#define MRBX_IPP_ONE_FROM_9(F)          F(9)  MRBX_IPP_ONE_FROM_8(F)
#define MRBX_IPP_ONE_FROM_10(F)         F(10) MRBX_IPP_ONE_FROM_9(F)
#define MRBX_IPP_ONE_FROM_11(F)         F(11) MRBX_IPP_ONE_FROM_10(F)
#define MRBX_IPP_ONE_FROM_12(F)         F(12) MRBX_IPP_ONE_FROM_11(F)
#define MRBX_IPP_ONE_FROM_13(F)         F(13) MRBX_IPP_ONE_FROM_12(F)
#define MRBX_IPP_ONE_FROM_14(F)         F(14) MRBX_IPP_ONE_FROM_13(F)
#define MRBX_IPP_ONE_FROM_15(F)         F(15) MRBX_IPP_ONE_FROM_14(F)
#define MRBX_IPP_ONE_FROM_16(F)         F(16) MRBX_IPP_ONE_FROM_15(F)
#define MRBX_IPP_ONE_FROM_17(F)         F(17) MRBX_IPP_ONE_FROM_16(F)
#define MRBX_IPP_ONE_FROM_18(F)         F(18) MRBX_IPP_ONE_FROM_17(F)
#define MRBX_IPP_ONE_FROM_19(F)         F(19) MRBX_IPP_ONE_FROM_18(F)
#define MRBX_IPP_ONE_FROM_20(F)         F(20) MRBX_IPP_ONE_FROM_19(F)
#define MRBX_IPP_ONE_FROM_21(F)         F(21) MRBX_IPP_ONE_FROM_20(F)
#define MRBX_IPP_ONE_FROM_22(F)         F(22) MRBX_IPP_ONE_FROM_21(F)
#define MRBX_IPP_ONE_FROM_23(F)         F(23) MRBX_IPP_ONE_FROM_22(F)
#define MRBX_IPP_ONE_FROM_24(F)         F(24) MRBX_IPP_ONE_FROM_23(F)
#define MRBX_IPP_ONE_FROM_25(F)         F(25) MRBX_IPP_ONE_FROM_24(F)
#define MRBX_IPP_ONE_FROM_26(F)         F(26) MRBX_IPP_ONE_FROM_25(F)
#define MRBX_IPP_ONE_FROM_27(F)         F(27) MRBX_IPP_ONE_FROM_26(F)
#define MRBX_IPP_ONE_FROM_28(F)         F(28) MRBX_IPP_ONE_FROM_27(F)
#define MRBX_IPP_ONE_FROM_29(F)         F(29) MRBX_IPP_ONE_FROM_28(F)
#define MRBX_IPP_ONE_FROM_30(F)         F(30) MRBX_IPP_ONE_FROM_29(F)
#define MRBX_IPP_ONE_FROM_31(F)         F(31) MRBX_IPP_ONE_FROM_30(F)
#define MRBX_IPP_ONE_FROM_32(F)         F(32) MRBX_IPP_ONE_FROM_31(F)
#define MRBX_IPP_ONE_FROM_33(F)         F(33) MRBX_IPP_ONE_FROM_32(F)
#define MRBX_IPP_ONE_FROM_34(F)         F(34) MRBX_IPP_ONE_FROM_33(F)
#define MRBX_IPP_ONE_FROM_35(F)         F(35) MRBX_IPP_ONE_FROM_34(F)
#define MRBX_IPP_ONE_FROM_36(F)         F(36) MRBX_IPP_ONE_FROM_35(F)
#define MRBX_IPP_ONE_FROM_37(F)         F(37) MRBX_IPP_ONE_FROM_36(F)
#define MRBX_IPP_ONE_FROM_38(F)         F(38) MRBX_IPP_ONE_FROM_37(F)
#define MRBX_IPP_ONE_FROM_39(F)         F(39) MRBX_IPP_ONE_FROM_38(F)
#define MRBX_IPP_ONE_FROM_40(F)         F(40) MRBX_IPP_ONE_FROM_39(F)
#define MRBX_IPP_ONE_FROM_41(F)         F(41) MRBX_IPP_ONE_FROM_40(F)
#define MRBX_IPP_ONE_FROM_42(F)         F(42) MRBX_IPP_ONE_FROM_41(F)
#define MRBX_IPP_ONE_FROM_43(F)         F(43) MRBX_IPP_ONE_FROM_42(F)
#define MRBX_IPP_ONE_FROM_44(F)         F(44) MRBX_IPP_ONE_FROM_43(F)
#define MRBX_IPP_ONE_FROM_45(F)         F(45) MRBX_IPP_ONE_FROM_44(F)
#define MRBX_IPP_ONE_FROM_46(F)         F(46) MRBX_IPP_ONE_FROM_45(F)
#define MRBX_IPP_ONE_FROM_47(F)         F(47) MRBX_IPP_ONE_FROM_46(F)
#define MRBX_IPP_ONE_FROM_48(F)         F(48) MRBX_IPP_ONE_FROM_47(F)
#define MRBX_IPP_ONE_FROM_49(F)         F(49) MRBX_IPP_ONE_FROM_48(F)
#define MRBX_IPP_ONE_FROM_50(F)         F(50) MRBX_IPP_ONE_FROM_49(F)

#define MRBX_IPP_ZERO_FROM_0(F)         F(0)
#define MRBX_IPP_ZERO_FROM_1(F)         F(1)  MRBX_IPP_ZERO_FROM_0(F)
#define MRBX_IPP_ZERO_FROM_2(F)         F(2)  MRBX_IPP_ZERO_FROM_1(F)
#define MRBX_IPP_ZERO_FROM_3(F)         F(3)  MRBX_IPP_ZERO_FROM_2(F)
#define MRBX_IPP_ZERO_FROM_4(F)         F(4)  MRBX_IPP_ZERO_FROM_3(F)
#define MRBX_IPP_ZERO_FROM_5(F)         F(5)  MRBX_IPP_ZERO_FROM_4(F)
#define MRBX_IPP_ZERO_FROM_6(F)         F(6)  MRBX_IPP_ZERO_FROM_5(F)
#define MRBX_IPP_ZERO_FROM_7(F)         F(7)  MRBX_IPP_ZERO_FROM_6(F)
#define MRBX_IPP_ZERO_FROM_8(F)         F(8)  MRBX_IPP_ZERO_FROM_7(F)
#define MRBX_IPP_ZERO_FROM_9(F)         F(9)  MRBX_IPP_ZERO_FROM_8(F)
#define MRBX_IPP_ZERO_FROM_10(F)        F(10) MRBX_IPP_ZERO_FROM_9(F)
#define MRBX_IPP_ZERO_FROM_11(F)        F(11) MRBX_IPP_ZERO_FROM_10(F)
#define MRBX_IPP_ZERO_FROM_12(F)        F(12) MRBX_IPP_ZERO_FROM_11(F)
#define MRBX_IPP_ZERO_FROM_13(F)        F(13) MRBX_IPP_ZERO_FROM_12(F)
#define MRBX_IPP_ZERO_FROM_14(F)        F(14) MRBX_IPP_ZERO_FROM_13(F)
#define MRBX_IPP_ZERO_FROM_15(F)        F(15) MRBX_IPP_ZERO_FROM_14(F)
#define MRBX_IPP_ZERO_FROM_16(F)        F(16) MRBX_IPP_ZERO_FROM_15(F)
#define MRBX_IPP_ZERO_FROM_17(F)        F(17) MRBX_IPP_ZERO_FROM_16(F)
#define MRBX_IPP_ZERO_FROM_18(F)        F(18) MRBX_IPP_ZERO_FROM_17(F)
#define MRBX_IPP_ZERO_FROM_19(F)        F(19) MRBX_IPP_ZERO_FROM_18(F)
#define MRBX_IPP_ZERO_FROM_20(F)        F(20) MRBX_IPP_ZERO_FROM_19(F)
#define MRBX_IPP_ZERO_FROM_21(F)        F(21) MRBX_IPP_ZERO_FROM_20(F)
#define MRBX_IPP_ZERO_FROM_22(F)        F(22) MRBX_IPP_ZERO_FROM_21(F)
#define MRBX_IPP_ZERO_FROM_23(F)        F(23) MRBX_IPP_ZERO_FROM_22(F)
#define MRBX_IPP_ZERO_FROM_24(F)        F(24) MRBX_IPP_ZERO_FROM_23(F)
#define MRBX_IPP_ZERO_FROM_25(F)        F(25) MRBX_IPP_ZERO_FROM_24(F)
#define MRBX_IPP_ZERO_FROM_26(F)        F(26) MRBX_IPP_ZERO_FROM_25(F)
#define MRBX_IPP_ZERO_FROM_27(F)        F(27) MRBX_IPP_ZERO_FROM_26(F)
#define MRBX_IPP_ZERO_FROM_28(F)        F(28) MRBX_IPP_ZERO_FROM_27(F)
#define MRBX_IPP_ZERO_FROM_29(F)        F(29) MRBX_IPP_ZERO_FROM_28(F)
#define MRBX_IPP_ZERO_FROM_30(F)        F(30) MRBX_IPP_ZERO_FROM_29(F)
#define MRBX_IPP_ZERO_FROM_31(F)        F(31) MRBX_IPP_ZERO_FROM_30(F)
#define MRBX_IPP_ZERO_FROM_32(F)        F(32) MRBX_IPP_ZERO_FROM_31(F)
#define MRBX_IPP_ZERO_FROM_33(F)        F(33) MRBX_IPP_ZERO_FROM_32(F)
#define MRBX_IPP_ZERO_FROM_34(F)        F(34) MRBX_IPP_ZERO_FROM_33(F)
#define MRBX_IPP_ZERO_FROM_35(F)        F(35) MRBX_IPP_ZERO_FROM_34(F)
#define MRBX_IPP_ZERO_FROM_36(F)        F(36) MRBX_IPP_ZERO_FROM_35(F)
#define MRBX_IPP_ZERO_FROM_37(F)        F(37) MRBX_IPP_ZERO_FROM_36(F)
#define MRBX_IPP_ZERO_FROM_38(F)        F(38) MRBX_IPP_ZERO_FROM_37(F)
#define MRBX_IPP_ZERO_FROM_39(F)        F(39) MRBX_IPP_ZERO_FROM_38(F)
#define MRBX_IPP_ZERO_FROM_40(F)        F(40) MRBX_IPP_ZERO_FROM_39(F)
#define MRBX_IPP_ZERO_FROM_41(F)        F(41) MRBX_IPP_ZERO_FROM_40(F)
#define MRBX_IPP_ZERO_FROM_42(F)        F(42) MRBX_IPP_ZERO_FROM_41(F)
#define MRBX_IPP_ZERO_FROM_43(F)        F(43) MRBX_IPP_ZERO_FROM_42(F)
#define MRBX_IPP_ZERO_FROM_44(F)        F(44) MRBX_IPP_ZERO_FROM_43(F)
#define MRBX_IPP_ZERO_FROM_45(F)        F(45) MRBX_IPP_ZERO_FROM_44(F)
#define MRBX_IPP_ZERO_FROM_46(F)        F(46) MRBX_IPP_ZERO_FROM_45(F)
#define MRBX_IPP_ZERO_FROM_47(F)        F(47) MRBX_IPP_ZERO_FROM_46(F)
#define MRBX_IPP_ZERO_FROM_48(F)        F(48) MRBX_IPP_ZERO_FROM_47(F)
#define MRBX_IPP_ZERO_FROM_49(F)        F(49) MRBX_IPP_ZERO_FROM_48(F)
#define MRBX_IPP_ZERO_FROM_50(F)        F(50) MRBX_IPP_ZERO_FROM_49(F)

#define MRBX_IPP_COUNT_ARGS30_1(...)                                    \
  MRBX_IPP_COUNT_ARGS30_2(__VA_ARGS__,                                  \
                          30, 30, 30, 30, 30, 30, 30, 30, 30, 30, /* C コンパイラによって引数エラーを報告させる */ \
                          30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, \
                          14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0, [[<<>>]]) \

#define MRBX_IPP_COUNT_ARGS30_2(_00, _01, _02, _03, _04, _05, _06, _07, _08, _09, _10, _11, _12, _13, _14, \
                                _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, \
                                _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, ARGC, ...) ARGC \

#define MRBX_IPP_TEXTIZE_1(...) MRBX_IPP_TEXTIZE_2(__VA_ARGS__)
#define MRBX_IPP_TEXTIZE_2(...) # __VA_ARGS__ "\n"

#endif /* MRUBY_AUX_INTERNALS_PP_H */
