name: build and test

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  ubuntu:
    runs-on: ubuntu-24.04
    name: ubuntu-24.04 (mruby-${{matrix.TARGET_MRUBY}})
    strategy:
      matrix:
        TARGET_MRUBY:
        - master
        - 3.3.0
        - 3.2.0
        - 3.1.0
        - 3.0.0
        #- 2.1.2
        #- 2.1.1
        #- 2.1.0
        #- 2.0.1
        #- 2.0.0
        #- 1.4.1
        #- 1.4.0
        #- 1.3.0
        #- 1.2.0
    env:
      MRUBY_URL: "https://github.com/mruby/mruby/archive/${{matrix.TARGET_MRUBY}}.tar.gz"
      MRUBY_DIR: "mruby-${{matrix.TARGET_MRUBY}}"
      MRUBY_CONFIG: ../ci_config.rb
      CC: clang
    steps:
    - uses: actions/checkout@v4
    - name: fetch and extract mruby
      run: wget -O- $MRUBY_URL | tar xzf -
    - name: build
      run: |
        rake -vE 'Dir.chdir "mruby-${{matrix.TARGET_MRUBY}}"' clean
        rake -mvE 'Dir.chdir "mruby-${{matrix.TARGET_MRUBY}}"' || rake -vE 'Dir.chdir "mruby-${{matrix.TARGET_MRUBY}}"'
    - name: test
      run: rake -vE 'Dir.chdir "mruby-${{matrix.TARGET_MRUBY}}"' test
